---
title: "Emphasizing Humanity in the Statistical Analysis of Auschwitz Victims"
author: 
  - Victor Ma
thanks: "Code and data are available at: https://github.com/bestmustard/holocaust-victims. Interactive graphs and tables are available at: https://f0t0w3-victor-ma.shinyapps.io/holocaust-victims-shinyapp/ and https://f0t0w3-victor-ma.shinyapps.io/aushwitz-prisoners-deports/"
date: today
date-format: long
format: pdf
number-sections: true
bibliography: references.bib
---

# Data

In my analysis of the Holocaust victims killed at Auschwitz concentration camp, I pull data from 70.auschwitz.org- a website dedicated to commemorating Auschwitz victims and survivors which provides relevant data on the demographics of victims, prisoners, and those who were deported. This site is operated by Państwowe Muzeum Auschwitz-Birkenau w Oświęcimiu, a museum on the site of the concentration camp. Visualizations with the shiny package are written in the data manipulation language R [@aus, @shiny, @citeR].

The shiny app provides an interactive graph and table of the number of victims killed by nationality. The categories are separated into: Jews, Poles, Roma(Gypsies), Soviet Prisoners of War, and Other Groups. This categorization is not accurate to what we would call nationality today- "Jews" are better described as an ethnoreligious group and "Roma Gypsies" are an ethnic group. From the data, we can see that 85% of the deportees were classified was Jewish. 10.8% were "Poles", or Polish and the other groups took up a collective 4.7%. Despite Polish people being the second most relevant figure and almost 10 times greater than all other groups respectively, they had the lowest percentage of deaths at 46%. According to the museum site, 900 of the 1.1 million total deaths were Jews murdered in gas chambers immediately on arrival [@aus]. 

The below tables give us many more details in terms of demographics, which are replications of the tables on the Auschwitz museum site [@aus]. They can also be found at: https://f0t0w3-victor-ma.shinyapps.io/aushwitz-prisoners-deports/.


| Country of Origin                                 | Number  |
|---------------------------------------------------|--------:|
| Hungary (according to the borders during the war) | 430,000 |
| Poland                                            | 300,000 |
| France                                            |  69,000 |
| The Netherlands                                   |  60,000 |
| Greece                                            |  55,000 |
| The Protectorate of Bohemia and Moravia (Theresienstadt) |  46,000 |
| Concentration camps and other centers             |  34,000 |
| Slovakia (according to the borders during the war) |  27,000 |
| Belgium                                           |  25,000 |
| Germany and Austria                               |  23,000 |
| Yugoslavia                                        |  10,000 |
| Italy                                             |   7,500 |
| Norway                                            |     690 |
: Jews Deported to Auschwitz by Country of Origin {#tbl-jews}


| Nationality        | Number    |
|--------------------|----------:|
| Jews               | 200,000   |
| Poles              | 140,000   |
| Roma               | 21,000    |
| Soviet captives    | 12,000    |
| Czech              | 9,000     |
| Belarussian        | 6,000     |
| German             | 4,000     |
| French             | 4,000     |
| Russian            | 1,500     |
| Yugoslavian        | 800       |
| Ukrainian          | 500       |
| Other              | 200       |

: Prisoners by Ethnic Background {#tbl-pris}

From @tbl-jews, we can see that the highest number of deportees came from Hungary and Poland, with a great disparity in numbers compared to the next highest country being France. According to Yehuda Bauer's "Rethinking the Holocaust", Hungary had the highest remaining population of Jewish people at the time of German invasion, with a population o 825,000 [@bauer]. This placement also made sense geographically given the proximity of Auschwitz to Hungary. 

# Discussion

When we deal with data, we look for trends to explore, and patterns to extrapolate from. However, in the case of horrific events like this, it can be insensitive to represent profound human tragedy through a cold and detached medium. While on one hand such quantification is important for getting the history right and understanding it, on the other hand, it poses the danger of turning people into nothing but raw statistics. This is a point most scholars voice with regard to the ethics of data. Comparing the demographic sizes of deportees and prisoners gives us a stark reminder of the genocide's targeted nature. 69% of the prisoners, comprised completely of Jews, died upon arrival. Through data we can group these people by their religion and cause of death, but its important to remember them as more than numbers, recognizing their humanity and the lives they lived.

Translating the life narratives into data points of human beings is a difficult exercise which seems to underline a friction in historic and sociological research. How does one reconcile the need for completely detailed analysis while giving thought to individual human experiences? This is the dual moral from statistical analyses that scholars such as Joanna Bourke make: although they are very useful to reveal the large-scale pattern of violence, they carry with them a moral double risk of anonymizing the subject, so as to be able to aid commemoration [@bourke]. This challenge is not unique to Holocaust studies but is a factor in all efforts to quantify human suffering.

Eviatar Zerubavel's work on social memory reminds us that remembering can be very selective, as groups can choose what kind of memories to keep; he points out that quantification can be revealing or obfuscating with regard to events in history [@zerubavel]. This is also what the narrative out of the data measures and gets reported in statistical terms.

The project approach to the visualization of Auschwitz victim data carries with it a kind of balance between quantification, required for the analytic utility, and sensitivities to the deep individuality of the victims. Kieran Healy reflects on data analysis and points out to very serious ethical responsibilities of handling data about human lives [@healy2020]. He notes that though data can sometimes first come off as something abstract and faceless, in reality, it is the representation of real people and communities with their stories and suffering.

This project is not just an exercise in data analysis but a tribute to the victims it represents. Using data about such a horror reminds data scientists of the importance of retaining a fair respect for limitations and potentials for dehumanization. It serves as a reminder that behind every data point lies a human story, deserving of remembrance and dignity.

\newpage

# References

::: {#refs}
:::